version: '3.8'
services:
  web:
    container_name: app
    build:
      context: ./
      target: runner
    volumes:
      - .:/app
    command: yarn dev
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      NODE_ENV: development